name: notebook
channels:
  - conda-forge
dependencies:
  - ipywidgets=8
  - jupyterlab=4
  - jupyterlab-language-pack-fr-FR
  - matplotlib
  - numpy
  - nodejs=20
  - python >=3.13,<3.14
  - xeus-python
